name = "gabon-occaz"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[build]
command = "npm install --legacy-peer-deps && npx @cloudflare/next-on-pages@1"
